version: 2.1

parameters:
  action:
    type: enum
    enum: [build, deploy]
    default: build

jobs:
  build-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Build"
          command: echo "ビルド用のジョブです！"
  deploy-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Deployment"
          command: echo "デプロイ用のジョブです！"

workflows:
  build-workflow:
    when:
      equal: [ build, << pipeline.parameters.action >> ]
    jobs:
      - build-job

  deploy-workflow:
    when:
      equal: [ deploy, << pipeline.parameters.action >> ]
    jobs:
      - deploy-job:
          filters:
            branches:
              only:
                - main
